### ISSUE TITLE
Fatal error on second upgrade

### ISSUE THREAD

**Issue by dianabarsan** [medic/horticulturalist#22]
When trying to perform the second upgrade, horti crashes when trying to overwrite an existing symlink. 

```
  horti:debug Primary ddoc written +3s
Updating symlinks for changed apps… [ { name: 'medic-api',
    attachmentName: 'medic-api-0.1.0.tgz',
    digest: 'md5-wmKqGbAc5bAKugPtyXZdKQ==',
    deployPath: [Function: deployPath] } ]
********FATAL********
{ Error: EEXIST: file already exists, symlink '/home/user/.horticulturalist/deployments/medic-api/md5-vU2CqBOkCe+HMwOM3oCb+w==' -> '/home/user/.horticulturalist/deployments/medic-api/old'
    at Object.fs.symlinkSync (fs.js:1031:18)
    at Promise.all.changedApps.map.app (/usr/lib/node_modules/horticulturalist/src/install/deploySteps.js:112:14)
    at Array.map (<anonymous>)
    at updateSymlink (/usr/lib/node_modules/horticulturalist/src/install/deploySteps.js:105:36)
    at Promise.resolve.then.then (/usr/lib/node_modules/horticulturalist/src/install/deploySteps.js:153:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  errno: -17,
  code: 'EEXIST',
  syscall: 'symlink',
  path: '/home/user/.horticulturalist/deployments/medic-api/md5-vU2CqBOkCe+HMwOM3oCb+w==',
  dest: '/home/user/.horticulturalist/deployments/medic-api/old' }
```

**Comment by SCdF** [comment]
@dianabarsan is this from one version to the same version again, yeah? Not just generally the second time you upgrade something?

Also, perhaps we should check with @garethbowen, but my understanding is that we're still raising tickets against medic-webapp regardless of the project so they will be noticed and worked on in our normal flow.

**Comment by garethbowen** [comment]
@SCdF Ahh that explains how I missed this one! Yes I find it easier if all issues are in medic-webapp.

**Comment by dianabarsan** [comment]
@SCdF no, it does not matter if you're upgrading to the same version or not. 
The idea is that the `old` symlink is not deleted prior to trying to write it again. 

I'll copy it to webapp.

**Comment by garethbowen** [comment]
Copied here: medic/medic-webapp#4800
