### ISSUE TITLE
Horti --local timing out connections to build server

### ISSUE THREAD

**Issue by kennsippell** [medic/horticulturalist#63]
Having some horti problems. 

```
$ horti --local --install=3.11.0
Starting Horticulturalist 0.13.1 daemon in local mode
...
********FATAL********
{ FetchError: request to https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A3.11.0/ddocs/sentinel.json?rev=1-70af7383c5b1a708fe2538803798ea9c failed, reason: connect ETIMEDOUT 18.135.111.134:443
    at ClientRequest.<anonymous> (/usr/lib/node_modules/horticulturalist/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A3.11.0/ddocs/sentinel.json?rev=1-70af7383c5b1a708fe2538803798ea9c failed, reason: connect ETIMEDOUT 18.135.111.134:443',
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  docId: 'medic%3Amedic%3A3.11.0' }
```

```
horti --version
Horticulturalist 0.13.1
```

same result for 3.10.3, 3.13.0, etc

**Comment by Hareet** [comment]
It's working fine for me. We haven't heard of anyone else experiencing this issue. 

I upgraded and launched new ones for the last half hour and it was stable. 

Next time it happens, can you share the time of day? This will help us determine if the staging server is having issues under load

**Comment by kennsippell** [comment]
Interesting. I can consistently reproduce it for ~2.5 days. Let me investigate conditions on my end. Sounds like it's me, not you.

**Comment by mrjones-plip** [comment]
I did some very lite testing when this ticket was opened (a la `curl -o /dev/null  https://staging.dev.medicmobile.org/_couch/builds/medic:medic:3.13.0/medic-api-0.1.0.tgz`) and it looked OK - I forgot to report this though - sorry!
